[[LLVMTblgen]]
arch = "x86_64"
git-tree-sha1 = "0eaebd40916149984099ad57772a8a24a38ae31d"
libc = "glibc"
os = "linux"

    [[LLVMTblgen.download]]
    sha256 = "ff693b1fd3a7a62dc2143db93387023256ca07188ba5657c417506b9b9dfeb1a"
    url = "https://github.com/staticfloat/LLVMTblgen_jll.jl/releases/download/v17.0.0-GCCBootstrap-x86_64-linux-gnu/LLVMTblgen-v17.0.0-x86_64-linux-gnu.tar.gz"

[[LLVMTblgen-build_log]]
arch = "x86_64"
git-tree-sha1 = "56ef1be16b7a14fd100f1fac1e218a802ab4d799"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMTblgen-build_log.download]]
    sha256 = "fe378d9f451fc83ca46398c5cd37f9f54d3fb9bc5a8aa55a4116f5572324cda5"
    url = "https://github.com/staticfloat/LLVMTblgen_jll.jl/releases/download/v17.0.0-GCCBootstrap-x86_64-linux-gnu/LLVMTblgen-build_log-v17.0.0-x86_64-linux-gnu.tar.gz"

[[LLVMTblgen-extract_log]]
arch = "x86_64"
git-tree-sha1 = "64f22773b89a6b6bd4fbeec2d83e52498ff71cc2"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMTblgen-extract_log.download]]
    sha256 = "8568b454e421b3582265b395d356f38ad2b3df298380f15c9f2e7041705cea48"
    url = "https://github.com/staticfloat/LLVMTblgen_jll.jl/releases/download/v17.0.0-GCCBootstrap-x86_64-linux-gnu/LLVMTblgen-extract_log-v17.0.0-x86_64-linux-gnu.tar.gz"
