[[LLVMTblgen]]
arch = "x86_64"
git-tree-sha1 = "b04ef090c8df076886fa808abec3b8fb78797620"
libc = "glibc"
os = "linux"

    [[LLVMTblgen.download]]
    sha256 = "50454b09d2561637c24f92552ed845ed856a5fcf7ca11a3f0dfcaee0e9862c9b"
    url = "https://github.com/staticfloat/LLVMTblgen_jll.jl/releases/download/v17.0.0/LLVMTblgen-v17.0.0-x86_64-linux-gnu.tar.gz"

[[LLVMTblgen-build_log]]
arch = "x86_64"
git-tree-sha1 = "5804ab80788bbdea456fba346b0627240c2d86a1"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMTblgen-build_log.download]]
    sha256 = "357bc0a5b8140a26e6527a486df4f41a6a0ff03dd6496eb33367e7c5453d6389"
    url = "https://github.com/staticfloat/LLVMTblgen_jll.jl/releases/download/v17.0.0/LLVMTblgen-build_log-v17.0.0-x86_64-linux-gnu.tar.gz"

[[LLVMTblgen-extract_log]]
arch = "x86_64"
git-tree-sha1 = "c381d1ce4ba8e39d7c7d79c8a6c1ef6231497165"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMTblgen-extract_log.download]]
    sha256 = "e41ba59999eb669a911ab200091b42d2d89fc777c23c271cc3ad1c245bc68666"
    url = "https://github.com/staticfloat/LLVMTblgen_jll.jl/releases/download/v17.0.0/LLVMTblgen-extract_log-v17.0.0-x86_64-linux-gnu.tar.gz"
