[[LLVMTblgen]]
arch = "x86_64"
git-tree-sha1 = "775866d3ed9384a4a68b54d529adc6747690b97a"
libc = "glibc"
os = "linux"

    [[LLVMTblgen.download]]
    sha256 = "9bb9841b3cd0188490844f2607814ef794bb918d368b0ff3def4e132115a9d27"
    url = "https://github.com/staticfloat/LLVMTblgen_jll.jl/releases/download/v17.0.0/LLVMTblgen-v17.0.0-x86_64-linux-gnu.tar.gz"

[[LLVMTblgen-build_log]]
arch = "x86_64"
git-tree-sha1 = "66263c490d4822e33706c0045032db12f3517f9a"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMTblgen-build_log.download]]
    sha256 = "f5893e3de7bc1b9e1d8ff48f47ed412ddf6a2cdad498b93c4b1e7c476fb2e829"
    url = "https://github.com/staticfloat/LLVMTblgen_jll.jl/releases/download/v17.0.0/LLVMTblgen-build_log-v17.0.0-x86_64-linux-gnu.tar.gz"

[[LLVMTblgen-extract_log]]
arch = "x86_64"
git-tree-sha1 = "69e649455edcc5f39c462bc437a5b647ce65ba3c"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMTblgen-extract_log.download]]
    sha256 = "1abd6b7520db5475acef035fb050b6de0dc9dd1573a5f0e54d573f4c49508af5"
    url = "https://github.com/staticfloat/LLVMTblgen_jll.jl/releases/download/v17.0.0/LLVMTblgen-extract_log-v17.0.0-x86_64-linux-gnu.tar.gz"
