[[LLVMTblgen]]
arch = "x86_64"
git-tree-sha1 = "ad2821f11ffc6be09a972fc9bf3149f5d646263a"
libc = "glibc"
os = "linux"

    [[LLVMTblgen.download]]
    sha256 = "4ca35ac802b7995c19afcce6a64eb4bd4337be8394f058fddead0fbd84ce8854"
    url = "https://github.com/staticfloat/LLVMTblgen_jll.jl/releases/download/v17.0.0/LLVMTblgen-v17.0.0-x86_64-linux-gnu.tar.gz"

[[LLVMTblgen-build_log]]
arch = "x86_64"
git-tree-sha1 = "4bed29e4cf657907fdbd8eced8383a62232be468"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMTblgen-build_log.download]]
    sha256 = "9203b3b6262356615678ec20a2705c3cf06a1ba0ed9f561c3efbea401a3fd09e"
    url = "https://github.com/staticfloat/LLVMTblgen_jll.jl/releases/download/v17.0.0/LLVMTblgen-build_log-v17.0.0-x86_64-linux-gnu.tar.gz"

[[LLVMTblgen-extract_log]]
arch = "x86_64"
git-tree-sha1 = "c5ee75eb22c97098f8cfed7651369c8da1bac78b"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMTblgen-extract_log.download]]
    sha256 = "80fc038930ebfbb81b756813fa9a860abe15539f1f13b020750c5bb6888d9634"
    url = "https://github.com/staticfloat/LLVMTblgen_jll.jl/releases/download/v17.0.0/LLVMTblgen-extract_log-v17.0.0-x86_64-linux-gnu.tar.gz"
