[[LLVMTblgen]]
arch = "x86_64"
git-tree-sha1 = "b04ef090c8df076886fa808abec3b8fb78797620"
libc = "glibc"
os = "linux"

    [[LLVMTblgen.download]]
    sha256 = "9b2a1846cdcb500f8e00e4565eb6876c5186c0cede12b7875e4838340e5640b4"
    url = "https://github.com/staticfloat/LLVMTblgen_jll.jl/releases/download/v17.0.0/LLVMTblgen-v17.0.0-x86_64-linux-gnu.tar.gz"

[[LLVMTblgen-build_log]]
arch = "x86_64"
git-tree-sha1 = "36d165a4311aa6719762a67d85f8cab32c774b6f"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMTblgen-build_log.download]]
    sha256 = "53b5bb756dab8a5f38016b3b13f3bfa13e25732e8cce715fee092deacd0b1325"
    url = "https://github.com/staticfloat/LLVMTblgen_jll.jl/releases/download/v17.0.0/LLVMTblgen-build_log-v17.0.0-x86_64-linux-gnu.tar.gz"

[[LLVMTblgen-extract_log]]
arch = "x86_64"
git-tree-sha1 = "57399c0fbb66bfcc3c57e20eb9dc35bd1d201355"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMTblgen-extract_log.download]]
    sha256 = "a95afd6064cd6aa05cbb0834518a983b988279649a60fd7fbc86a989267713e9"
    url = "https://github.com/staticfloat/LLVMTblgen_jll.jl/releases/download/v17.0.0/LLVMTblgen-extract_log-v17.0.0-x86_64-linux-gnu.tar.gz"
