[[LLVMTblgen]]
arch = "x86_64"
git-tree-sha1 = "b04ef090c8df076886fa808abec3b8fb78797620"
libc = "glibc"
os = "linux"

    [[LLVMTblgen.download]]
    sha256 = "87abb82e317dfab1e4ba5813bdc32b3e439774cfd85882b694f38c4a038d64cf"
    url = "https://github.com/staticfloat/LLVMTblgen_jll.jl/releases/download/v17.0.0/LLVMTblgen-v17.0.0-x86_64-linux-gnu.tar.gz"

[[LLVMTblgen-build_log]]
arch = "x86_64"
git-tree-sha1 = "2690dc87253d90668910bb9ccba23ce1679d808a"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMTblgen-build_log.download]]
    sha256 = "4e0441410d7050ea3173701058d481b4c8df82c217d7d6723db2f2af2642ef33"
    url = "https://github.com/staticfloat/LLVMTblgen_jll.jl/releases/download/v17.0.0/LLVMTblgen-build_log-v17.0.0-x86_64-linux-gnu.tar.gz"

[[LLVMTblgen-extract_log]]
arch = "x86_64"
git-tree-sha1 = "5744017b9e006239df028692b85eea37641d054c"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMTblgen-extract_log.download]]
    sha256 = "60d63c702b486000fb0f788bcff6fb412af69dd494f7d298ebeee54a1fcf8fb2"
    url = "https://github.com/staticfloat/LLVMTblgen_jll.jl/releases/download/v17.0.0/LLVMTblgen-extract_log-v17.0.0-x86_64-linux-gnu.tar.gz"
