[[LLVMTblgen]]
arch = "x86_64"
git-tree-sha1 = "0eaebd40916149984099ad57772a8a24a38ae31d"
libc = "glibc"
os = "linux"

    [[LLVMTblgen.download]]
    sha256 = "119bbf277a64bdbea8eba7f511d690cd7411846c168b4b4f85c7ad3e525aea02"
    url = "https://github.com/staticfloat/LLVMTblgen_jll.jl/releases/download/v17.0.0-GCCBootstrap-x86_64-linux-gnu/LLVMTblgen-v17.0.0-x86_64-linux-gnu.tar.gz"

[[LLVMTblgen-build_log]]
arch = "x86_64"
git-tree-sha1 = "f9aca3f26d6426b636dff30d5edb077b42242597"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMTblgen-build_log.download]]
    sha256 = "53dc3293c33b05a3f98fcf78a3fa084ac7b11752d3844d8503ff66008953f9ac"
    url = "https://github.com/staticfloat/LLVMTblgen_jll.jl/releases/download/v17.0.0-GCCBootstrap-x86_64-linux-gnu/LLVMTblgen-build_log-v17.0.0-x86_64-linux-gnu.tar.gz"

[[LLVMTblgen-extract_log]]
arch = "x86_64"
git-tree-sha1 = "d8f5b6ec5d7d750b1ea8988f6d7118adb7232c39"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMTblgen-extract_log.download]]
    sha256 = "0c1d5a8f18e7f047634ddf523c111125f1487b65b40e472d82a56ce672e79f83"
    url = "https://github.com/staticfloat/LLVMTblgen_jll.jl/releases/download/v17.0.0-GCCBootstrap-x86_64-linux-gnu/LLVMTblgen-extract_log-v17.0.0-x86_64-linux-gnu.tar.gz"
