[[LLVMTblgen]]
arch = "x86_64"
git-tree-sha1 = "0eaebd40916149984099ad57772a8a24a38ae31d"
libc = "glibc"
os = "linux"

    [[LLVMTblgen.download]]
    sha256 = "6a68162314c6d2b440537f3dd700c3aadb184c8cd0656a4624644ef0ebaa32c3"
    url = "https://github.com/staticfloat/LLVMTblgen_jll.jl/releases/download/v17.0.0-GCCBootstrap-x86_64-linux-gnu/LLVMTblgen-v17.0.0-x86_64-linux-gnu.tar.gz"

[[LLVMTblgen-build_log]]
arch = "x86_64"
git-tree-sha1 = "783ee233b4ff9ecff91a222759d4e4444e32ed49"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMTblgen-build_log.download]]
    sha256 = "5cba9ce4c63c59766363713283847407f064e80a28426bfbaeab6361c9e2e715"
    url = "https://github.com/staticfloat/LLVMTblgen_jll.jl/releases/download/v17.0.0-GCCBootstrap-x86_64-linux-gnu/LLVMTblgen-build_log-v17.0.0-x86_64-linux-gnu.tar.gz"

[[LLVMTblgen-extract_log]]
arch = "x86_64"
git-tree-sha1 = "d0a565c602b54e57e6bc93e206d7cb8c58c923c7"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMTblgen-extract_log.download]]
    sha256 = "ec5fbb0af30e866d47579ea8e1a56306f7b26748f30ab4638b4ebc6adb6ae89d"
    url = "https://github.com/staticfloat/LLVMTblgen_jll.jl/releases/download/v17.0.0-GCCBootstrap-x86_64-linux-gnu/LLVMTblgen-extract_log-v17.0.0-x86_64-linux-gnu.tar.gz"
