[[LLVMTblgen]]
arch = "x86_64"
git-tree-sha1 = "3b093d8f8570b8a74a378d659ebd1ba113b9bc64"
libc = "glibc"
os = "linux"

    [[LLVMTblgen.download]]
    sha256 = "72d5c7640985919d99155874eaa5bc737e247776b8aa13515c892569f0311fe5"
    url = "https://github.com/staticfloat/LLVMTblgen_jll.jl/releases/download/v17.0.0/LLVMTblgen-v17.0.0-x86_64-linux-gnu.tar.gz"

[[LLVMTblgen-build_log]]
arch = "x86_64"
git-tree-sha1 = "4571cd437e3b2f60d44060afbac6107ee811a92a"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMTblgen-build_log.download]]
    sha256 = "f739e63e3406bfeb3a6b631aaf88a556bf94b090dcf0c92c6098652bd1dfd71d"
    url = "https://github.com/staticfloat/LLVMTblgen_jll.jl/releases/download/v17.0.0/LLVMTblgen-build_log-v17.0.0-x86_64-linux-gnu.tar.gz"

[[LLVMTblgen-extract_log]]
arch = "x86_64"
git-tree-sha1 = "2312d7eb3e6ff478a4df6b432b09fd1d3cf709bb"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMTblgen-extract_log.download]]
    sha256 = "1fe66d8dead5e545448044879fd77e1fbda2c08c55ad16524ac36c0d001bc191"
    url = "https://github.com/staticfloat/LLVMTblgen_jll.jl/releases/download/v17.0.0/LLVMTblgen-extract_log-v17.0.0-x86_64-linux-gnu.tar.gz"
