[[LLVMTblgen]]
arch = "x86_64"
git-tree-sha1 = "b04ef090c8df076886fa808abec3b8fb78797620"
libc = "glibc"
os = "linux"

    [[LLVMTblgen.download]]
    sha256 = "6581edc3cb7cf0307a468b12d1db2bb3bc315c87586e1f42dccafe1d3f381320"
    url = "https://github.com/staticfloat/LLVMTblgen_jll.jl/releases/download/v17.0.0/LLVMTblgen-v17.0.0-x86_64-linux-gnu.tar.gz"

[[LLVMTblgen-build_log]]
arch = "x86_64"
git-tree-sha1 = "8ed9f77f47207cb4ee476e403c81d5f883653115"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMTblgen-build_log.download]]
    sha256 = "ddba16f45cb34a4bd9ed768756e8640f9d503409fcd5ba120502b11b8ab5558c"
    url = "https://github.com/staticfloat/LLVMTblgen_jll.jl/releases/download/v17.0.0/LLVMTblgen-build_log-v17.0.0-x86_64-linux-gnu.tar.gz"

[[LLVMTblgen-extract_log]]
arch = "x86_64"
git-tree-sha1 = "bfa232aee3bd5cbd2e7e0f4400bc50c0c12ebdc6"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMTblgen-extract_log.download]]
    sha256 = "ed37a56f198819845a0eb844133327449d0fc1e362c44e706efb4ca6304a9726"
    url = "https://github.com/staticfloat/LLVMTblgen_jll.jl/releases/download/v17.0.0/LLVMTblgen-extract_log-v17.0.0-x86_64-linux-gnu.tar.gz"
